Cleanup more u32 being used as pointers.
zeldaret/oot pull request #1052
Opened 2021-12-02 02:29 UTC by louist103

2021-12-02 02:32 UTC, fig02 approved these changes

2021-12-02 07:23 UTC, Dragorn421 requested changes

2021-12-02 07:23 UTC, Dragorn421 commented on include/z64.h
> +            /* 0x10 */ void*   tlut;
Can you align the field names 😊

2021-12-02 15:40 UTC, Dragorn421 commented on include/z64.h
> +    /* 0x04 */ Gfx* dlist;
😊

2021-12-06 23:40 UTC, fig02 commented
something got messed up while you were updating variable names

2021-12-07 11:05 UTC, Dragorn421 commented on include/z64scene.h
> +} Path;                       // size = 0x8
```suggestion
} Path; // size = 0x8
```

2021-12-07 19:08 UTC, Roman971 approved these changes

2021-12-07 19:19 UTC, merged