Name some misc. symbols.
zeldaret/oot pull request #1058
Opened 2021-12-04 11:34 UTC by Meowsy

This is mostly just renaming empty functions to be `[Class]_DoNothing`. The rest of the changes are just some low-hanging fruit I felt relatively confident in.

2021-12-04 12:08 UTC, Dragorn421 requested changes
Thanks for your contribution! some comments
(not giving you the cold shoulder in comments, we just usually get to the point on reviews without pleasantries or it would take ages)

2021-12-04 12:08 UTC, Dragorn421 commented on src/overlays/actors/ovl_Bg_Spot18_Obj/z_bg_spot18_obj.c
> +static BgSpot18ObjInitFunc sInitFuncs2[] = {
then this can drop the 2
```suggestion
static BgSpot18ObjInitFunc sInitFuncs[] = {
```

2021-12-04 12:39 UTC, Meowsy commented on src/overlays/actors/ovl_En_Ik/z_en_ik.c
> +static EnIkDrawFunc sDrawFuncs[] = { EnIk_DoNothing, func_80A77EDC, func_80A77844 };
Whoops, missed that one.

2021-12-04 12:53 UTC, Meowsy commented
> Thanks for your contribution! some comments (not giving you the cold shoulder in comments, we just usually get to the point on reviews without pleasantries or it would take ages)
No worries; I'm bad at pleasantries myself.

2021-12-04 15:05 UTC, Dragorn421 commented on src/overlays/actors/ovl_Bg_Spot18_Obj/z_bg_spot18_obj.c
> +static BgSpot18ObjInitFunc sInitFuncs1[] = {
When I said
> I would leave it unnamed until more functions are named in this actor
I meant the name should probably stay `D_808B910C` unless you can think of a better name

2021-12-04 19:38 UTC, Meowsy commented on src/overlays/actors/ovl_Bg_Spot18_Obj/z_bg_spot18_obj.c
> +static BgSpot18ObjInitFunc sInitFuncs1[] = {
I somehow managed to not stage *only* the lines related to `D_808B910C`. I don't even understand how.

2021-12-04 19:42 UTC, Dragorn421 approved these changes

2021-12-07 16:50 UTC, fig02 commented
Im a little wary of naming every empty function in an actor as "do nothing". The ones that are called do nothing currently are done so cause it makes sense in the context of the actor.
For example, in darkmeiro, its called "noop" as in no operation on purpose-- the function callbacks arent really actions in this case, they are basically update functions. So no operation is more appropriate than do nothing

I would prefer if they got named with the whole actor being documented so we are sure the name makes sense in that context

2021-12-27 18:49 UTC, fig02 commented
I'm going to close this for now, for the reasons mentioned above. I hope this doesn't discourage you from getting into doing documentation work though. Its just pretty important for us that this stuff is done at the system level so that all context can be taken into account.
I recommend picking an actor to document in-full instead of naming a bunch of similar functions in different actors. Let me know if you have any questions are reach out on the discord.

2021-12-27 18:49 UTC, closed without merging