Updating vscode.md
zeldaret/oot pull request #1095
Opened 2021-12-26 16:16 UTC by srmeier

Updating `vscode.md` to match what is found in the [mm repository](https://github.com/zeldaret/mm/blob/master/docs/tutorial/vscode.md).

This provides an example cpp configuration JSON which helped my solve an issue I was facing.

2021-12-26 17:59 UTC, Dragorn421 requested changes

2021-12-26 17:59 UTC, Dragorn421 commented on docs/tutorial/vscode.md
> +## Useful stuff to know:
```suggestion
## Useful keyboard shortcuts
```

2021-12-26 17:59 UTC, Dragorn421 commented on docs/tutorial/vscode.md
> +        "nonmatchings/**": true,
```suggestion
```
may be a mm thing, oot doesn't have this folder and never did afaik

2021-12-26 17:59 UTC, Dragorn421 commented on docs/tutorial/vscode.md
> +- ~~bracket pair colorizer 2~~ (now obsolete due to VSCode's built-in bracket colouring)
```suggestion
```
no need to mention it anymore then

2021-12-26 19:37 UTC, Dragorn421 approved these changes

2021-12-29 00:57 UTC, EllipticEllipsis reviewed
Looks good, but maybe it should move out of the tutorial folder now?

2021-12-30 01:12 UTC, srmeier commented
> Looks good, but maybe it should move out of the tutorial folder now?

Where would make more sense?

2021-12-30 06:27 UTC, EllipticEllipsis commented
Probably the root of the docs folder for now? We're bound to restructure it soon anyway, if we decide to put actual documentation of the repo itself in there.

2021-12-30 20:10 UTC, srmeier commented
Sounds good, moved `vscode.md` to the docs folder.

2021-12-30 20:12 UTC, EllipticEllipsis approved these changes

2021-12-30 20:12 UTC, EllipticEllipsis commented on docs/vscode.md
> +Add the following to (or create) the `.vscode/settings.json` file for VSCode to search the gitignored asset and assembly files by default:
Actually, OoT doesn't do this
```suggestion
Add the following to (or create) the `.vscode/settings.json` file for VSCode to search the gitignored asset files by default:
```

2022-01-06 19:53 UTC, srmeier commented
@EllipticEllipsis Updated based on your previous comments.

2022-01-06 19:58 UTC, EllipticEllipsis approved these changes

2022-01-17 00:57 UTC, fig02 approved these changes

2022-01-17 23:35 UTC, Roman971 approved these changes

2022-01-17 23:35 UTC, merged