Whitespace
zeldaret/oot pull request #1112
Opened 2022-01-19 15:19 UTC by playerskel

Not much to say really.

2022-01-19 16:16 UTC, Dragorn421 requested changes

2022-01-19 16:16 UTC, Dragorn421 commented on include/z64camera.h
> +
```suggestion
```

2022-01-19 16:16 UTC, Dragorn421 commented on src/overlays/actors/ovl_En_Fz/z_en_fz.h
> +    /* 0x0030 */ f32 xyScale; //
```suggestion
    /* 0x0030 */ f32 xyScale;
```

2022-01-19 16:48 UTC, fig02 approved these changes
after the changes above are addressed this is fine for me.

some changes in here were not whitespace related, though im sure it was an accident when splitting up your bigger pr. just something to keep in mind in general though. its fine that they stay in

2022-01-20 05:26 UTC, playerskel commented on src/overlays/actors/ovl_En_Fz/z_en_fz.h
> +    /* 0x0030 */ f32 xyScale; //
Done.

2022-01-20 05:26 UTC, playerskel commented on include/z64camera.h
> +
Done.

2022-01-20 10:41 UTC, Dragorn421 approved these changes

2022-01-23 23:07 UTC, Roman971 approved these changes

2022-01-23 23:09 UTC, merged