Decompiled En_Holl
zeldaret/oot pull request #253
Opened 2020-07-13 23:45 UTC by Thar0

I don't like submitting nonmatching actors but my hand has been forced.
1 non-matching remaining, regalloc only.
Partially documented.

2020-07-18 00:03 UTC, Thar0 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> +        gDPSetPrimColor(gfxP++, 0, 0, 0, 0, 0, (u8)this->planeAlpha);
Cast is necessary to match

2020-07-18 00:04 UTC, Thar0 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + * [1] : Load the room on the other side of the loading plane
I updated the comment to try and clarify a bit more, would appreciate feedback on the change

2020-07-18 00:05 UTC, Thar0 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + *      you can load the room on the other side multiple times
Do you have any suggestions as to where these comments could be moved to? I feel like there's no one place in the code that contributes to these bugs so wasn't sure where to put it in the code itself, this was more of a temporary place just to have those documented.

2020-07-18 22:50 UTC, Roman971 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + *      you can load the room on the other side multiple times
I'm not sure, but I think somewhere more general like init or update would already be better.
Either way, I'm also not convinced the fact that actors can unload between rooms belongs as a bug, or at least it's not limited to this actor's behaviour.

2020-07-18 22:52 UTC, fig02 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + *      you can load the room on the other side multiple times
I said the same thing. It feels like the bug is moreso how you can get around to the other side of these in the first place.
But tharo said that ideally the bug is fixed in this actor (for future modding purposes), so it should definitely be mentioned somewhere in this file, but maybe not with a bug tag

2020-07-18 22:53 UTC, Roman971 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + * [1] : Load the room on the other side of the loading plane
I'm not sure this is the best way to describe them, but with this new sentence the comments on the last 2 values should at least be updated.

2020-07-18 22:55 UTC, Roman971 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + *      you can load the room on the other side multiple times
Well I was referring specifically about the bug on "Object Lists conflicts", which is a general issue with how room transitions are handled. Tho it feels more like a limitation than a bug to me.

2020-07-18 22:58 UTC, fig02 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + *      you can load the room on the other side multiple times
oh I see. the problem is specific to this implementation of different "stripes" of loading triggers for the black planes though, right? obv the root cause is object dependencies in general, but it really becomes an issue for this specific method of loading the next room

2020-07-18 23:00 UTC, Roman971 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + *      you can load the room on the other side multiple times
I don't think so, but I could be wrong.

2020-07-19 19:52 UTC, fig02 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> + * [1] : Load the room on the other side of the loading plane
if we can take some time in discord soon to discuss these remaining documentation issues itd be good i think

2020-08-21 02:07 UTC, fig02 commented
i forget is there anything we need to figure out with this file?

2020-09-27 02:48 UTC, fig02 commented
do we want to merge and get back to the documentation stuff at a later time? I think its probably the best move.
Just got some conflicts to resolve @Thar0

2020-09-27 21:12 UTC, fig02 approved these changes
code looks good to me, and like we said we'll get to docs another time :D

2020-09-30 18:00 UTC, Roman971 requested changes

2020-09-30 18:00 UTC, Roman971 commented on src/overlays/actors/ovl_En_Holl/z_en_holl.c
> +    Gfx* dispRefs[4];
This function needs to be updated to use OPEN_DISPS/CLOSE_DISPS.

2020-09-30 18:50 UTC, Roman971 approved these changes

2020-09-30 19:11 UTC, merged