Decomp EnExRuppy
zeldaret/oot pull request #331
Opened 2020-08-19 05:05 UTC by louist103

2020-08-19 20:11 UTC, Roman971 requested changes
This file needs to be formatted properly (mostly just need to run the format script).

I'll wait for formatting to do a full review so comments don't randomly get outdated

2020-08-23 21:49 UTC, Roman971 commented on src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
> +s16 Rupee_ID_Table[] = {
```suggestion
s16 sRupeeCollectibleTypes[] = {
```

2020-08-23 21:49 UTC, Roman971 commented on src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
> +    0x0001, 0x0005, 0x0014, 0x01F4, 0x0032,
```suggestion
    1, 5, 20, 500, 50,
```

2020-08-23 21:50 UTC, Roman971 commented on src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
> +void EnExRuppy_Collect(EnExRuppy* this, GlobalContext* globalCtx) {
maybe `WaitForCollection`?

2020-08-23 21:53 UTC, Roman971 commented on src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
> +void EnExRuppy_BlowUp(EnExRuppy* this, GlobalContext* globalCtx) {
maybe `WaitToBlowUp` or `WaitToBlowUpOnContact`? (or Explode instead of BlowUp)

2020-08-23 21:56 UTC, fig02 commented on src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
> +void EnExRuppy_BlowUp(EnExRuppy* this, GlobalContext* globalCtx) {
wait to blow up imo
is specifying on contact necessary? I havent read the whole file

2020-08-23 21:56 UTC, fig02 commented on src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
> +void EnExRuppy_Collect(EnExRuppy* this, GlobalContext* globalCtx) {
as collectible probably makes more sense from the perspective of the rupee

2020-08-23 21:57 UTC, Roman971 commented on src/overlays/actors/ovl_En_Ex_Ruppy/z_en_ex_ruppy.c
> +void EnExRuppy_BlowUp(EnExRuppy* this, GlobalContext* globalCtx) {
yeah it's probably better left as an implementation detail, and there aren't any variants that blow up under different conditions afaik

2020-08-28 17:53 UTC, Roman971 approved these changes

2020-08-28 23:45 UTC, merged