ovl_Effect_Ss_Extra
zeldaret/oot pull request #339
Opened 2020-08-22 20:15 UTC by maekclena

2020-08-23 18:45 UTC, fig02 commented
Are you in the discord? its much easier to communicate there if youre able to join

2020-08-23 20:16 UTC, maekclena commented
Sorry, I didn't realize the file was reserved. I will check out the discord but you can already add me on trello with the same username.

2020-08-23 20:19 UTC, fig02 commented
cool. No worries at all about it being reserved. Feel free to do any more effects if it interests you. Like I mentioned, I put all of my completed effects on the trello so you can be sure not to do one I have already completed

2020-08-30 12:32 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +    /* 0x01 */ SS_EXTRA_RISING_TIMER,
imo no need to mention that its a rising timer. SS_EXTRA_TIMER is fine

2020-08-30 12:33 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +
we currently call this objBankIndex in most places. we can probably shorten it to Idx eventually, but for now we can keep it consistent with the rest

2020-08-30 12:34 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +        temp = gSegments[6];
i would personally call this oldSeg6 since it stores the old one and then restores it at the end
(which is also pretty weird? lmfao)

2020-08-30 12:35 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +    if ((objIdx >= 0) && Object_IsLoaded(objCtx, objIdx)) {
is this object context temp definitely needed? Im thinking it could possible be omitted.

2020-08-30 12:36 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +    Graph_OpenDisps(dispRefs, globalCtx->state.gfxCtx, "../z_eff_ss_extra.c", 168);
we'eve recently added OPEN_DISPS and CLOSE_DISPS macros. feel free to ask any questions if using them is confusing

2020-08-30 12:36 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +    gfxCtx = globalCtx->state.gfxCtx;
id call this temp "object"

2020-09-02 19:59 UTC, maekclena commented
Thank you for the review. I started working on actor ovl_En_Part which I reserved on trello so don't worry about conflicts.

2020-09-03 21:46 UTC, Roman971 requested changes

2020-09-03 21:50 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> + * Description: Horseback Archery Points
true yeah. "Minigame Score Points" is probably good

2020-09-04 18:07 UTC, maekclena commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +    gSegments[6] = PHYSICAL_TO_VIRTUAL(object);
Is it the same for line [41](https://github.com/zeldaret/oot/pull/339/files#diff-ba90ba79021816d70e067bafa61e7211R41)?

2020-09-04 18:09 UTC, fig02 commented on src/overlays/effects/ovl_Effect_Ss_Extra/z_eff_ss_extra.c
> +    gSegments[6] = PHYSICAL_TO_VIRTUAL(object);
yes

2020-09-04 21:04 UTC, fig02 approved these changes

2020-09-04 21:18 UTC, Roman971 approved these changes

2020-09-04 21:22 UTC, merged