Decomp Heishi4 All OK
zeldaret/oot pull request #364
Opened 2020-08-30 01:11 UTC by louist103

2020-09-01 19:26 UTC, Roman971 requested changes
This file has some formatting issues that will be fixed with the format script. I'll wait for that before doing a full review so comments don't go outdated.

Also I believe this includes an accidental revert to an old version of the diff script.

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +static u32 EnHeishi4ReactionSet[] = { 0x00000006, 0x00000007 };
```suggestion
static u32 sFaceReactionSets[] = { 6, 7 };
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    osSyncPrintf(VT_FGCOL(PURPLE) " ☆☆☆☆☆ メッセージ完了！   ☆☆☆☆☆ %x\n\n" VT_RST, ((s32)thisx->params >> 8) & 0xF);
```suggestion
    osSyncPrintf(VT_FGCOL(PURPLE) " ☆☆☆☆☆ メッセージ完了！   ☆☆☆☆☆ %x\n\n" VT_RST, (thisx->params >> 8) & 0xF);
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +        ActorShape_Init(&thisx->shape, 0.0f, &ActorShadow_DrawFunc_Circle, 30.0f);
```suggestion
        ActorShape_Init(&thisx->shape, 0.0f, ActorShadow_DrawFunc_Circle, 30.0f);
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +        if ((gSaveContext.eventChkInf[8] & 1) != 0) {
```suggestion
        if (gSaveContext.eventChkInf[8] & 1) {
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +        if ((gSaveContext.eventChkInf[4] & 0x20) != 0) {
```suggestion
        if (gSaveContext.eventChkInf[4] & 0x20) {
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +            if (!gSaveContext.nightFlag) {
else if here imo

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +                if (this->unk_284 == 0) {
else if here as well imo

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    if (globalCtx->sceneNum == 77) {
The scene enum value should be used here.

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +        if (globalCtx->sceneNum != 33) {
The scene enum value should be used here.
Also else if here imo

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    } else {
early return here imo

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +            this->actionFunc = &func_80A56874;
```suggestion
            this->actionFunc = func_80A56874;
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    SkelAnime_ChangeAnim(&this->skelAnime, &D_0600C374, 1.0f, 0.0f, frames, 2, -10.0f);
Any chance the temp can be avoided here?
```suggestion
    this->unk_288 = SkelAnime_GetFrameCount(&D_0600C374);
    SkelAnime_ChangeAnim(&this->skelAnime, &D_0600C374, 1.0f, 0.0f, this->unk_288, 2, -10.0f);
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +            this->actionFunc = &func_80A56614;
```suggestion
            this->actionFunc = func_80A56614;
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    // thisx->posRot.pos = this->pos;
```suggestion
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    SkelAnime_Draw(globalCtx, this->skelAnime.skeleton, this->skelAnime.limbDrawTbl, EnHeishi_OverrideLimbDraw, 0,
```suggestion
    SkelAnime_Draw(globalCtx, this->skelAnime.skeleton, this->skelAnime.limbDrawTbl, EnHeishi_OverrideLimbDraw, NULL,
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.h
> +};
This isn't necessarily the best but here are my suggestions to improve the consistency of this enum:
```suggestion
typedef enum {
    /* 0x00 */ HEISHI4_AT_KAKRIKO_ENTRANCE,
    /* 0x04 */ HEISHI4_AT_IMPAS_HOUSE = 4,
    /* 0x07 */ HEISHI4_AT_MARKET_NIGHT_DYING = 7,
    /* 0x08 */ HEISHI4_AT_MARKET_NIGHT
} Heishi4Type;
```
Also we usually have it below the struct but that's not an actual rule so I guess it's w/e

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    this->params = thisx->params & 0xFF;
```suggestion
    this->type = thisx->params & 0xFF;
```

2020-09-02 18:42 UTC, Roman971 commented on src/overlays/actors/ovl_En_Heishi4/z_en_heishi4.c
> +    if (this->params == 7) {
The type enum value should be used here

2020-09-04 21:02 UTC, Roman971 approved these changes

2020-09-05 14:17 UTC, fig02 approved these changes

2020-09-05 14:18 UTC, merged