Decompiled ovl_Bg_Spot18_Shutter
zeldaret/oot pull request #395
Opened 2020-09-16 01:43 UTC by ethteck

2020-09-16 18:53 UTC, Dragorn421 requested changes
Cool,
This is used in goron city for blocking Darunia's room at both ages (with different switch flags), and the shop as child at night (if I'm reading the scene setups correctly, that sounds a bit weird)
The game scenes always use 0 for the higher variable byte so the `(this->dyna.actor.params >> 8) & 1 == 1` case which seems to be a sideways-sliding door looks like unused code :(

2020-09-16 18:53 UTC, Dragorn421 commented on src/overlays/actors/ovl_Bg_Spot18_Shutter/z_bg_spot18_shutter.c
> +    if (Math_ApproxF(&this->dyna.actor.posRot.pos.y, this->dyna.actor.initPosRot.pos.y + 180.0f, 1.44f) != 0) {
`Math_ApproxF` returns a boolean

2020-09-17 14:40 UTC, Dragorn421 approved these changes

2020-09-20 15:32 UTC, Roman971 approved these changes

2020-09-20 16:14 UTC, fig02 approved these changes

2020-09-20 16:14 UTC, merged