Decompile En_Crow (Guay Enemy)
zeldaret/oot pull request #444
Opened 2020-10-11 19:35 UTC by Zelllll

100% matching

2020-10-16 16:28 UTC, petrie911 requested changes
Nice work. A few comments.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.h
> +    /* 0x014C */ Vec3f unk_14C[4];
As per EffectSs_EnFire, these are the fire effect positions. It calls them firePos.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +            rot->y += 3072.0f * sinf(this->skelAnime.animCurrentFrame * 0.7853982f);
```suggestion
            rot->y += 0xC00 * sinf(this->skelAnime.animCurrentFrame * (M_PI / 4));
```
Assuming the above matches, of course.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +            rot->y += 5120.0f * sinf((this->skelAnime.animCurrentFrame + 2.5f) * 0.7853982f);
```suggestion
            rot->y += 0x1400 * sinf((this->skelAnime.animCurrentFrame + 2.5f) * (M_PI / 4));
```
Again, assuming it matches.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        this->actor.scale.y = this->actor.scale.x;
Can this be a chained assignment?

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +            Item_DropCollectible(globalCtx, &this->actor.posRot, 2);
```suggestion
            Item_DropCollectible(globalCtx, &this->actor.posRot, ITEM00_RUPEE_RED);
```

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        if (this->actor.params != 0) {
Possible ternary.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    if (this->actor.bgCheckFlags & 8) {
Possible ternary.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    if (this->actor.params != 0) {
Possible ternary.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +            this->aimRotY += 4096.0f + (4096.0f * Math_Rand_ZeroOne());
If it matches, you could use 0x1000 instead of 4096.0f.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +            this->aimRotX = -2048.0f - (Math_Rand_ZeroOne() * 2048.0f);
Same as above, 2048 is 0x800.

2020-10-16 16:28 UTC, petrie911 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +            this->aimRotX -= (1024.0f * Math_Rand_ZeroOne()) + 1024.0f;
1024 is 0x400

2020-10-18 23:43 UTC, Zelllll commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        vec = &this->unk_14C[(limbIndex >> 1) - 1];
Unfortunately it did not match.

2020-10-18 23:53 UTC, Zelllll commented
Alright I made all the suggested changes (that matched) however I could not get anything to match when using ternaries, but it might just be that I did something wrong.

2020-10-31 04:57 UTC, Kenix3 approved these changes
Looks good to me!

2020-11-01 17:27 UTC, Roman971 requested changes
A few things.
I also suggest using parens inside conditions with `&&`s or `||`s, to make them more readable and not require the reader to know every operator precedence rule.

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.h
> +    /* 0x0258 */ ColliderJntSphItem colliderItem[1];
```suggestion
    /* 0x0258 */ ColliderJntSphItem colliderItems[1];
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        for (i = 0; i != 8; i++) {
```suggestion
        for (i = 0; i < 8; i++) {
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        for (i = 0; i != 4; i++) {
```suggestion
        for (i = 0; i < 4; i++) {
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        if (func_8002DBB0(&this->actor, &this->actor.initPosRot) > 300.0f) {
else if here imo

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        if (this->actor.posRot.pos.y < this->actor.initPosRot.pos.y - 50.0f) {
else if here imo

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    if (Math_SmoothScaleMaxMinS(&this->actor.shape, this->aimRotX, 10, 0x100, 8) == 0 && skelanimeUpdated &&
```suggestion
    if (Math_SmoothScaleMaxMinS(&this->actor.shape.rot.x, this->aimRotX, 10, 0x100, 8) == 0 && skelanimeUpdated &&
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        Math_ApproxUpdateScaledS(&this->actor.shape, -0x100, 0x400);
```suggestion
        Math_ApproxUpdateScaledS(&this->actor.shape.rot.x, -0x100, 0x400);
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    DECR(this->timer);
Also relevant in other functions:
```suggestion
    if (this->timer != 0) {
        this->timer--;
    }
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        this->actor.waterY < -40.0f && Player_GetMask(globalCtx) != 2) {
```suggestion
        this->actor.waterY < -40.0f && Player_GetMask(globalCtx) != PLAYER_MASK_SKULL) {
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    if (this->timer == 0 || Player_GetMask(globalCtx) == 2 || this->collider.base.atFlags & 2 ||
```suggestion
    if (this->timer == 0 || Player_GetMask(globalCtx) == PLAYER_MASK_SKULL || this->collider.base.atFlags & 2 ||
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +        if (this->actor.colChkInfo.damageEffect || this->actor.colChkInfo.damage) {
```suggestion
        if ((this->actor.colChkInfo.damageEffect != 0) || (this->actor.colChkInfo.damage != 0)) {
```

2020-11-01 17:27 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    }
Considering this usage, the array you called `firePos` should probably be a generic `bodyPartsPos` array, used as the positions for specific body parts. This is probably true for any actor that gets burned with `EffectSsEnFire`.

2020-11-07 22:53 UTC, Zelllll commented
I made all of the changes that Roman requested, and resolved Petrie's comments about ternaries because I could not find a way to do that and get anything to match.

2020-11-15 18:36 UTC, Roman971 requested changes
Last things but otherwise this looks good to me now.

2020-11-15 18:36 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    if (this->timer) {
```suggestion
    if (this->timer != 0) {
```

2020-11-15 18:36 UTC, Roman971 commented on src/overlays/actors/ovl_En_Crow/z_en_crow.c
> +    if (this->timer) {
```suggestion
    if (this->timer != 0) {
```

2020-11-15 20:37 UTC, Zelllll commented
Alright I committed all of Roman's changes, and also added parens to if statements which I forgot to do before, so it should be good to merge.

2020-11-15 21:34 UTC, Roman971 approved these changes

2020-11-16 01:09 UTC, fig02 approved these changes

2020-11-16 01:10 UTC, merged