ovl_en_horse_zelda OK
zeldaret/oot pull request #471
Opened 2020-11-06 21:03 UTC by emilybrooks

2020-11-15 18:48 UTC, Kenix3 requested changes

2020-11-15 18:48 UTC, Kenix3 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.c
> +    this->actor.shape.rot.x = Math_atan2f(this->actor.posRot.pos.y - this->unk_1F4, 30.0f) * 10430.3779f;
This 10430.3779 is probably 0x8000/M_PI

2020-11-16 22:42 UTC, fig02 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.c
> +    { 0xEBB7, 0x007C, 0x1539, 0x07 }, { 0xF466, 0x0002, 0x11B9, 0x07 }, { 0xF47B, 0xFFDD, 0x11AF, 0x07 },
i would make the vec3s values decimal since they are probably coordinates

2020-11-16 22:42 UTC, fig02 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.h
> +    /* 0x01E8 */ s32 pad2;
are the pad variables completely unused? I would leave them as char arrays then since thats our universal sign for unused

2020-11-19 22:00 UTC, fig02 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.c
> +    { 60343, 124, 5433, 0x07 },    { 62566, 2, 4537, 0x07 },      { 62587, 65501, 4527, 0x07 },
oh the conversion here did not take sign into account, most of these really big numbers should actually be negative. the tool i use to convert does this too lol, its annoying

2020-11-19 22:01 UTC, fig02 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.c
> +} unknownStruct; // size = 0x7
oh and due to struct alignment this size is 8

2020-11-22 11:02 UTC, fig02 approved these changes

2020-11-23 17:56 UTC, Roman971 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.h
> +    /* 0x014C */ s32 actionIndex;
We normally just call this field `action`
```suggestion
    /* 0x014C */ s32 action;
```

2020-11-23 17:56 UTC, Roman971 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.c
> +    this->animationIndex += 1;
```suggestion
    this->animationIndex++;
```

2020-11-23 17:56 UTC, Roman971 commented on src/overlays/actors/ovl_En_Horse_Zelda/z_en_horse_zelda.c
> +        this->unk_1EC += 1;
```suggestion
        this->unk_1EC++;
```

2020-11-23 20:56 UTC, Roman971 approved these changes

2020-11-24 08:38 UTC, merged