dekunuts OK
zeldaret/oot pull request #664
Opened 2021-01-27 07:43 UTC by gamestabled

back at it again with the copy-pasted deku scrub actors

2021-01-27 07:46 UTC, gamestabled commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.h
> +    /* 0x019A */ volatile s16 unk_19A;
keyword volatile like this is nowhere else to be seen. So it has to be super fake, right? This was the only way I was able to make EnDekunuts_Init match, but I would gladly try any ideas

2021-01-30 02:20 UTC, louist103 requested changes

2021-01-30 02:20 UTC, louist103 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +extern AnimationHeader gDekuNutsSpitAnim;
We dont need to `extern ` these anymore since they are externed in the object file

2021-01-30 02:20 UTC, louist103 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +static DamageTable D_809EAB84 = {
```suggestion
static DamageTable sDamageTable= {
```

2021-01-30 02:20 UTC, louist103 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +        CollisionCheck_SetInfo(&thisx->colChkInfo, &D_809EAB84, &sColChkInfoInit);
```suggestion
        CollisionCheck_SetInfo(&thisx->colChkInfo, &sDamageTable, &sColChkInfoInit);
```

2021-01-30 02:20 UTC, louist103 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +    if ((this->animFlagAndTimer == 0x1000)) {
```suggestion
    if (this->animFlagAndTimer == 0x1000) {
```

2021-01-30 02:20 UTC, louist103 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +                           20.0f - ((this->skelAnime.curFrame * 20.0f) / Animation_GetLastFrame((void*)&gDekuNutsBurrowAnim)));
is the void* cast needed?

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +                this->runDirection = (s16)((phi_f0 * -8192.0f) + (f32)this->actor.yawTowardsPlayer);
```suggestion
                this->runDirection = (phi_f0 * -0x2000) + this->actor.yawTowardsPlayer;
```
These casts are unnecessary, I believe.

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +                phi_f0 = (0.0f <= (f32)diffRot) ? 1.0f : -1.0f;
```suggestion
                phi_f0 = (diffRot >= 0.0f) ? 1.0f : -1.0f;
```
Literal goes on the right. Also I think just having the `0.0f` forces the float conversion.

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +            this->runDirection = (s16)(this->actor.yawTowardsPlayer + 0x8000);
```suggestion
            this->runDirection = this->actor.yawTowardsPlayer + 0x8000;
```
This cast should also be unnecessary.

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +        this->actor.colChkInfo.mass = 0xFF;
```suggestion
        this->actor.colChkInfo.mass = MASS_IMMOVABLE;
```

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +    if ((this->collider.base.acFlags & AC_HIT) != 0) {
```suggestion
    if (this->collider.base.acFlags & AC_HIT) {
```

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +    } else if ((this->actor.colChkInfo.mass == 0xFF) && (globalCtx->actorCtx.unk_02 != 0)) {
```suggestion
    } else if ((this->actor.colChkInfo.mass == MASS_IMMOVABLE) && (globalCtx->actorCtx.unk_02 != 0)) {
```

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +        if ((this->collider.base.acFlags & 1) != 0) {
```suggestion
        if (this->collider.base.acFlags & AC_ON) {
```

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +    if (thisx->params == 0xA) {
You could make a define for this, since it's clear that `0xA` is the flower.

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +            if (ABS(diffRot) >= 0x2001) {
```suggestion
            if (ABS(diffRot) > 0x2000) {
```

2021-02-05 17:18 UTC, petrie911 commented on src/overlays/actors/ovl_En_Dekunuts/z_en_dekunuts.c
> +        EffectSsHahen_SpawnBurst(globalCtx, &effectPos, 3.0f, 0, 12, 3, 15, -1, 10, NULL);
are there any relevant enums/defines for these guys?

2021-02-12 19:28 UTC, Roman971 approved these changes

2021-02-12 22:22 UTC, fig02 approved these changes

2021-02-12 22:22 UTC, merged