EnMu header and pointer fixes
zeldaret/oot pull request #765
Opened 2021-04-07 05:29 UTC by liamnobel

2021-04-07 05:38 UTC, louist103 requested changes
It won't let me add comments on the following things that need to be fixed:
Line break on line 180, and 194
Remove line break from 202

2021-04-07 05:38 UTC, louist103 commented on src/overlays/actors/ovl_En_Mu/z_en_mu.c
>      switch (func_8010BDBC(&globalCtx->msgCtx)) {
```suggestion
    EnMu* this = THIS;
    
    switch (func_8010BDBC(&globalCtx->msgCtx)) {
```

2021-04-07 05:38 UTC, louist103 commented on src/overlays/actors/ovl_En_Mu/z_en_mu.c
> +    func_800343CC(globalCtx, thisx, &this->dialogState.unk_00, talkDist, EnMu_GetFaceReaction, EnMu_CheckDialogState);
```suggestion
    func_800343CC(globalCtx, &this->actor, &this->dialogState.unk_00, talkDist, EnMu_GetFaceReaction, EnMu_CheckDialogState);
```
If this doesn't work than change `this->actor` to `thisx`

2021-04-07 05:48 UTC, Zelllll commented
The name `dialogState` is not accurate. It should be called `npcInfo`, as that is what that struct handles.

2021-04-07 06:08 UTC, louist103 approved these changes

2021-04-07 06:11 UTC, Zelllll approved these changes

2021-04-09 23:20 UTC, fig02 approved these changes

2021-04-10 15:48 UTC, Roman971 approved these changes

2021-04-10 15:48 UTC, merged