z_ovl_bg_spot07_taki OK
zeldaret/oot pull request #766
Opened 2021-04-07 20:40 UTC by mzxrules

this was actually pretty easy to get

2021-04-07 22:25 UTC, AngheloAlf requested changes
Nice one!
Just a few small things.

2021-04-07 22:25 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +    DynaPolyActor_Init(&this->dyna, DPM_PLAYER);
```suggestion
    CollisionHeader* colHeader = NULL;

    DynaPolyActor_Init(&this->dyna, DPM_PLAYER);
```

2021-04-07 22:25 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +    DynaPoly_DeleteBgActor(globalCtx, &globalCtx->colCtx.dyna, this->dyna.bgId);
```suggestion
    BgSpot07Taki* this = THIS;

    DynaPoly_DeleteBgActor(globalCtx, &globalCtx->colCtx.dyna, this->dyna.bgId);
```

2021-04-07 22:25 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +    this->actionFunc(this, globalCtx);
```suggestion
    BgSpot07Taki* this = THIS;

    this->actionFunc(this, globalCtx);
```

2021-04-07 22:25 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +    frames = globalCtx->gameplayFrames;
```suggestion
    u32 pad;
    u32 frames;

    OPEN_DISPS(globalCtx->state.gfxCtx, "../z_bg_spot07_taki.c", 169);
    frames = globalCtx->gameplayFrames;
```

2021-04-07 22:25 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +    if (gSaveContext.linkAge == 0) {
```suggestion
    if (LINK_IS_ADULT) {
```

2021-04-07 22:25 UTC, AngheloAlf commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +    if (gSaveContext.linkAge != 0) {
```suggestion
    if (LINK_IS_CHILD) {
```

2021-04-09 23:20 UTC, fig02 approved these changes

2021-04-10 06:32 UTC, louist103 requested changes
Looks good.  Just one group of things.

2021-04-10 06:32 UTC, louist103 commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +        if (thisx->params == 0) {
```suggestion
        if (this->dyna.actor.params == 0) {
```
If possible.

2021-04-10 06:32 UTC, louist103 commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +        if (thisx->params == 0) {
```suggestion
        if (this->dyna.actor.params == 0) {
```
Same here.

2021-04-10 06:32 UTC, louist103 commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +        if (thisx->params == 0) {
```suggestion
        if (this->dyna.actor.params == 0) {
```

2021-04-10 06:32 UTC, louist103 commented on src/overlays/actors/ovl_Bg_Spot07_Taki/z_bg_spot07_taki.c
> +    } else if (thisx->params == 0) {
```suggestion
    } else if (this->dyna.actor.params == 0) {
```

2021-04-12 00:05 UTC, fig02 approved these changes

2021-04-12 01:20 UTC, Roman971 approved these changes

2021-04-12 01:33 UTC, merged