ovl_Efc_Erupc OK
zeldaret/oot pull request #773
Opened 2021-04-12 20:34 UTC by mzxrules

also pretty easy

2021-04-12 23:09 UTC, louist103 requested changes
Looks good.  Just some small things.

2021-04-12 23:09 UTC, louist103 commented on src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.c
> +
```suggestion
```

2021-04-12 23:09 UTC, louist103 commented on src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.c
> +    Actor_SetScale(thisx, 1.0f);
```suggestion
    Actor_SetScale(&this->actor, 1.0f);
```

2021-04-12 23:09 UTC, louist103 commented on src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.c
> +        Gfx_TwoTexScroll(globalCtx->state.gfxCtx, 0, 0U, this->unk150 * -4, 16, 128, 1, 0, this->unk150 * 12, 32, 32));
Are the `U`s required?

2021-04-12 23:09 UTC, louist103 commented on src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.c
> +    gfxCtx = globalCtx->state.gfxCtx;
```suggestion
    GraphicsContext*  gfxCtx = globalCtx->state.gfxCtx;;
    s16 i;
    s32 pad;
    
```

2021-04-12 23:09 UTC, louist103 commented on src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.c
> +Color_RGB8 D_8099D770[] = {
```suggestion
static Color_RGB8 D_8099D770[] = {
```

2021-04-12 23:09 UTC, louist103 commented on src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.h
> +typedef struct {
Offsets like in the actor struct.

2021-04-12 23:09 UTC, louist103 commented on src/overlays/actors/ovl_Efc_Erupc/z_efc_erupc.c
> +            particles->animTimer = (s8)(s32)(s8)(s32)Rand_ZeroFloat(10);
This seems really fake but until someone has a better idea I guess its OK.  Maybe leave a note though.

2021-04-25 19:03 UTC, fig02 approved these changes
changes made

2021-04-25 23:03 UTC, Roman971 approved these changes

2021-04-25 23:12 UTC, merged