Macros: `PLAYER` -> `GET_PLAYER(globalCtx)`, `ACTIVE_CAM` -> `GET_ACTIVE_CAM(globalCtx)`
zeldaret/oot pull request #921
Opened 2021-08-25 04:13 UTC by engineer124

Even though this change is currently in https://github.com/zeldaret/oot/pull/908, I did end up deciding to make a separate PR because there are many actors I changed in https://github.com/zeldaret/oot/pull/908 dealing with `subCam`, and these two bulk macro changes from that PR make it harder to find and review the changes to subCam. So the purpose of this PR is to make sure those `subCam` changes aren't missed in review.

In the end, this PR changes the two Macros in the title, and fills in cases where the usage of this Macro was missed, as well as fill in new cases where these new macros applies (eg. `GET_PLAYER(camera->globalCtx)`, `GET_ACTIVE_CAM(camera->globalCtx)`)

2021-08-25 11:30 UTC, Dragorn421 requested changes
Could be added to actorfixer.py:
```py
    "PLAYER": "GET_PLAYER(globalCtx)",
    "ACTIVE_CAM": "GET_ACTIVE_CAM(globalCtx)",
```

And the formatter should be run

2021-08-25 11:52 UTC, fig02 commented
this is not necessarily a change I want to see right now, but something in the back of my mind: 
We know that these systems are designed to be portable, meaning they can work in any gamestate. Even if its not how things turned out in practice, it was definitely the intent. And with some modifications you could in theory have a new gamestate that contains an actor context and these camera variables. So would it be worth making the arg less specific than `globalCtx`?

If we decide not to, then another question I have is: should this macro make iteslf clear that it belongs to global context/play state? ie `PLAY_GET_ACTIVE_CAM` (or whatever global context ends up becoming)

Just food for thought, dont think we could make these kinds of decisions until our naming scheme for gamestates/play state is ironed out and implemented

2021-08-28 18:18 UTC, Roman971 commented
I think this should be good besides the stuff Dragorn mentioned in his review?

2021-08-29 08:43 UTC, Dragorn421 approved these changes

2021-08-29 11:29 UTC, Roman971 approved these changes

2021-08-29 16:30 UTC, AngheloAlf commented on include/macros.h
> +#define GET_PLAYER(globalCtx) ((Player*)globalCtx->actorCtx.actorLists[ACTORCAT_PLAYER].head)
```suggestion
#define GET_PLAYER(globalCtx) ((Player*)(globalCtx)->actorCtx.actorLists[ACTORCAT_PLAYER].head)
```

2021-08-29 16:30 UTC, AngheloAlf commented on include/macros.h
> +#define GET_ACTIVE_CAM(globalCtx) globalCtx->cameraPtrs[globalCtx->activeCamera]
```suggestion
#define GET_ACTIVE_CAM(globalCtx) ((globalCtx)->cameraPtrs[(globalCtx)->activeCamera])
```

2021-08-30 02:56 UTC, engineer124 commented
> Could be added to actorfixer.py:
> 
> ```python
>     "PLAYER": "GET_PLAYER(globalCtx)",
>     "ACTIVE_CAM": "GET_ACTIVE_CAM(globalCtx)",
> ```

@AngheloAlf Similar to your comment in MM, 

"This is a bad idea, because `GET_PLAYER(globalCtx)` contains the word `PLAYER`, so running this script a second time would produce `GET_GET_PLAYER(globalCtx)(globalCtx)` and so on"

That would also apply here. So should I take them out here? Any alternatives?

2021-08-30 02:58 UTC, fig02 commented
unrelated to the thing above, youll need to merge master and fix a small conflict

2021-08-30 02:59 UTC, AngheloAlf commented
I suggest to remove it from actorfixer.py. It isn't a huge deal imo, and leaving it there would produce way more problems than it would solve.

2021-08-30 03:02 UTC, engineer124 commented
> I suggest to remove it from actorfixer.py. It isn't a huge deal imo, and leaving it there would produce way more problems than it would solve.

I agree

2021-08-30 03:09 UTC, fig02 approved these changes

2021-08-30 03:18 UTC, AngheloAlf approved these changes

2021-08-30 06:59 UTC, Dragorn421 commented
I fixed the actorfixer script to only match whole-words so it won't replace PLAYER in GET_PLAYER. If you want to make sure try running the script with the PLAYER -> GET_PLAYER replace

2021-08-30 15:59 UTC, fig02 commented
in that case we can add this back to actor-fixer and merge this in after

2021-08-31 10:21 UTC, Roman971 approved these changes

2021-08-31 10:22 UTC, merged