Match remaining z_room functions
zeldaret/oot pull request #978
Opened 2021-09-19 06:57 UTC by Synray

2021-09-19 08:18 UTC, Dragorn421 requested changes

2021-09-19 08:18 UTC, Dragorn421 commented on src/code/z_room.c
> +    iREG(87) = polygon2->num & 0xffff & 0xffff & 0xffff; // if this is real then I might not be
```suggestion
    iREG(87) = polygon2->num & 0xFFFF & 0xFFFF & 0xFFFF; // if this is real then I might not be
```
at least you can be unreal in all caps

2021-09-19 11:59 UTC, Dragorn421 approved these changes

2021-09-19 13:43 UTC, Roman971 approved these changes

2021-09-20 19:37 UTC, fig02 approved these changes

2021-09-20 19:37 UTC, merged